### ISSUE TITLE
Engine is undefined

### ISSUE THREAD

**Issue by t-morgan** [udacity/frontend-nanodegree-arcade-game#5]
I wanted to give players the option to play again (after running into too many bugs and losing all of their lives), so I created a modal pop-up with a button that effectively calls init() from within Engine. However, Engine was coming back as undefined... to get around this, I am returning {'init': init} to be able to call Engine.init().

As other Udacity students may have problems with this, what would be a good way to handle this case going forward?

**Comment by wstoettinger** [comment]
I ran into the same problem. It's not possible to refernce the Engine object anywhere. Any updates?

**Comment by wstoettinger** [comment]
i solved this by adding these lines at the end of the Engine Object, right below global.ctx = ctx;

  global.Engine = {
    init: init, // makes the init function globally available via Engine.init();
    reset: reset // makes a custom reset function globally available via Engine.reset();
    // add further functions as needed
  };

**Comment by carlospnav** [comment]
From what I tested, and by reading the code, it seems to me, the problem is that the var Engine is assigned the result of an immediately invoked function expression that returns nothing. A function with nothing returned, resolves to undefined. Using IIFEs, from what I've learned, is a good way to maintain code accessible within a file but not  to other files in the same environment (which prevents nomenclature conflicts in other files that might have functions or variables with similar names). Removing the IIFE thereby assigning a regular function to Engine and invoking it soon after, solves the root of the problem, in my opinion.
